### ISSUE TITLE
Strong Name for UnityWCF

### ISSUE THREAD

**Issue by dsxp** [Uriil/unitywcf#1]
Hi there!

Can be the nuget assembly (UnityWCF) strong named?

Thanks!

**Comment by Uriil** [comment]
Hi, sure, i will do it

**Comment by dsxp** [comment]
Thanks!

And thanks for all your hard work!

Best regards!

**Comment by Uriil** [comment]
Done

**Comment by dsxp** [comment]
Awesome! thanks a lot!
