### ISSUE TITLE
Hello, can you consult the question MT4 manager APi?

### ISSUE THREAD

**Issue by anymorefree** [Uriil/unitywcf#7]
Excuse me, how to use the MT4 Manager Api to connect the heartbeat operation？
How to increase the amount of concurrent orders？
Because I found on my machine, a single connection open order, up to only 4 single per second,
However, if I use multi-threaded operation, APi will return a lot of strange exceptions, I use the method of multiple connections, the effect is not very good
   Looking forward for your reply, thank you

**Comment by Uriil** [comment]
Hi, you won't be able to use single connection for concurrent requests.

The only way is to use concurrent connections.

However if you will connect to MT4 server from local network it will be
much faster, that's the way we were doing

**Comment by anymorefree** [comment]
Thank you for your reply.
Do I need to maintain the heartbeat for each connection and MT4 server when using multiple connections?
I now solve this concurrency problem, is there any need to improve it?
![image](https://user-images.githubusercontent.com/14011170/32686806-38ed0f50-c6e8-11e7-9078-263af2702839.png)

**Comment by Uriil** [comment]
If you are not using pumping mode and delay between orders is significant,
yes, you need heartbeat

**Comment by anymorefree** [comment]
I understand, thank you very much for your reply
