### ISSUE TITLE
Unity.Wcf Merge

### ISSUE THREAD

**Issue by viceice** [Uriil/unitywcf#8]
Hi,

I'm the maintainer of [Unity.Wcf](https://www.nuget.org/packages/Unity.Wcf/). We should merge our projects.

The project will move to the official organisation unitycontainer/unity#12

**Comment by Uriil** [comment]
Perfect.

How can I help?

**Comment by viceice** [comment]
You can publish a package redirect. Simply an empty package wich depends on `Unity.Wcf` 😄

**Comment by Uriil** [comment]
Done
